/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Business.CarAppDir;
import Business.CarDetails;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anish
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private JPanel rightpanel;
    private CarAppDir cd;

    CreateJPanel(JPanel rightpanel, CarAppDir cd) {
        initComponents();
        this.rightpanel=rightpanel;
        this.cd=cd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        car_details_label = new javax.swing.JLabel();
        lbl_model = new javax.swing.JLabel();
        txt_model = new javax.swing.JTextField();
        lbl_company = new javax.swing.JLabel();
        txt_company = new javax.swing.JTextField();
        lbl_serno = new javax.swing.JLabel();
        txt_serno = new javax.swing.JTextField();
        plate_label = new javax.swing.JLabel();
        txt_manu = new javax.swing.JTextField();
        lbl_seats = new javax.swing.JLabel();
        txt_seats = new javax.swing.JTextField();
        availability_label = new javax.swing.JLabel();
        lbl_city = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        MCD_label = new javax.swing.JLabel();
        txt_expired = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        lbl_certificates = new javax.swing.JLabel();
        lbl_manu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_avail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        car_details_label.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        car_details_label.setText("Enter Car Details");

        lbl_model.setText("Model Number :");

        txt_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modelActionPerformed(evt);
            }
        });

        lbl_company.setText("Company Name :");

        lbl_serno.setText("Serial No :");

        txt_manu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manuActionPerformed(evt);
            }
        });

        lbl_seats.setText("No of Seats:");

        txt_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatsActionPerformed(evt);
            }
        });

        lbl_city.setText("City :");

        txt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cityActionPerformed(evt);
            }
        });

        save_btn.setText("SAVE");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        lbl_certificates.setText("Expired Certificates :");

        lbl_manu.setText("Manufactured date :");

        jLabel1.setText("Available :");

        jButton1.setText("<<back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_company)
                    .addComponent(lbl_serno)
                    .addComponent(lbl_seats)
                    .addComponent(plate_label)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MCD_label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(161, 161, 161)
                        .addComponent(car_details_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_model)
                            .addComponent(lbl_city)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbl_manu))
                            .addComponent(lbl_certificates)
                            .addComponent(jLabel1))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_expired, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(availability_label, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_serno, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_manu, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_avail, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(car_details_label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_city)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_manu)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_model)
                            .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_company))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_serno)
                            .addComponent(txt_serno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plate_label)
                            .addComponent(lbl_seats)
                            .addComponent(txt_seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_manu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availability_label)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_avail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_certificates)
                    .addComponent(txt_expired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MCD_label)
                    .addComponent(save_btn))
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        CarDetails Carr=cd.addCar();
         try{
        Integer.parseInt(txt_model.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid model name");
                return;
        }
        int Model_Number1=Integer.parseInt(txt_model.getText());
        try{
        Integer.parseInt(txt_manu.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid brand name");
                return;
        }
        int plate_no1=Integer.parseInt(txt_manu.getText());
        try{
        Integer.parseInt(txt_seats.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid seating capacity");
                return;
        }
        int Seating_capacity1=Integer.parseInt(txt_seats.getText());
        if(txt_company.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid company name");
                return;
                }
        
        String Brand_Name1=txt_company.getText();
         if(txt_serno.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid serial number");
                return;
                }
        String ser_no1=txt_serno.getText();  
        if(txt_city.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid city");
                return;
                }
        String City1=txt_city.getText();
        if(txt_expired.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid expiry case");
                return;
                }
        String MDC1=txt_expired.getText();
        if(txt_avail.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid availability case");
                return;
                }
        String avail=txt_avail.getText();

        
        Carr.setModel_Number(Model_Number1);
        Carr.setCar_Manufacturers(Brand_Name1);
        Carr.setSerial_Number(ser_no1);
        Carr.setYear_Manufacture(plate_no1);
        Carr.setSeating_capacity(Seating_capacity1);
        Carr.setCar_City(City1);
        Carr.setCar_Expired(MDC1);
        Carr.setAvail_car(avail);
        JOptionPane.showMessageDialog(null," Successfully Created!!");
        
    }//GEN-LAST:event_save_btnActionPerformed

    private void txt_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modelActionPerformed

    private void txt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cityActionPerformed

    private void txt_manuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manuActionPerformed

    private void txt_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout=(CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MCD_label;
    private javax.swing.JLabel availability_label;
    private javax.swing.JLabel car_details_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_certificates;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_company;
    private javax.swing.JLabel lbl_manu;
    private javax.swing.JLabel lbl_model;
    private javax.swing.JLabel lbl_seats;
    private javax.swing.JLabel lbl_serno;
    private javax.swing.JLabel plate_label;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField txt_avail;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_expired;
    private javax.swing.JTextField txt_manu;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_seats;
    private javax.swing.JTextField txt_serno;
    // End of variables declaration//GEN-END:variables
}
