/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Business.CarAppDir;
import Business.CarDetails;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anish
 */
public class FindCarsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form FindCarsJpanel
     */
    private JPanel rightpanel;
    private CarAppDir cd;
    FindCarsJpanel(JPanel rightpanel, CarAppDir cd) {
        initComponents();
        this.rightpanel=rightpanel;
        this.cd=cd;
        populateTablee();
    }
     private void populateTablee()
    {
        DefaultTableModel dtm=(DefaultTableModel)Car_table2.getModel();
        dtm.setRowCount(0);
        for(CarDetails Carr : cd.getCar())
        {
            Object[]row=new Object[8];
            row[0]=Carr;
            row[1]=Carr.getCar_Manufacturers();
            row[2]=Carr.getSerial_Number();
            row[3]=Carr.getSeating_capacity();
            row[4]=Carr.getCar_City();
            row[5]=Carr.getYear_Manufacture();
            row[6]=Carr.getAvail_car();
            row[7]=Carr.getCar_Expired();
            
            
            dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Car_table2 = new javax.swing.JTable();
        availCars_label = new javax.swing.JLabel();
        availCars_field = new javax.swing.JTextField();
        UnavailCars_field = new javax.swing.JTextField();
        avail_cars_label = new javax.swing.JLabel();
        max_min_label = new javax.swing.JLabel();
        Max_field = new javax.swing.JTextField();
        Min_field = new javax.swing.JTextField();
        display_label = new javax.swing.JLabel();
        Search_serialno_label = new javax.swing.JLabel();
        SearchBrand_label = new javax.swing.JLabel();
        SearchBrand_Field = new javax.swing.JTextField();
        SearchModel_label = new javax.swing.JLabel();
        car_ser_no_field = new javax.swing.JTextField();
        availcars_label = new javax.swing.JLabel();
        model_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        avail_cars_btn = new javax.swing.JButton();
        maxmin_btn = new javax.swing.JButton();
        count_btn = new javax.swing.JButton();
        car_brand_btn = new javax.swing.JButton();
        car_ser_no_btn = new javax.swing.JButton();
        model_btn = new javax.swing.JButton();
        mfg_btn = new javax.swing.JButton();
        expired_mfg_btn = new javax.swing.JButton();
        nearest_car_btn = new javax.swing.JButton();
        list_car_brands_btn = new javax.swing.JButton();
        UnavailCars_label = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        catupd_btn = new javax.swing.JButton();
        catupd_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        man_yeartxt = new javax.swing.JTextField();
        Brandtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        Car_table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model ", "Brand", "Serial ", "Seating", "City", "Year", "Avail", "Expired"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Car_table2);

        availCars_label.setText("Available Cars :");

        avail_cars_btn.setText("All available cars in the city :");
        avail_cars_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avail_cars_btnActionPerformed(evt);
            }
        });

        maxmin_btn.setText("Available Cars with seats(max,min):");
        maxmin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxmin_btnActionPerformed(evt);
            }
        });

        count_btn.setText("Display count of Avail & Unavail cars:");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });

        car_brand_btn.setText("Search Car via Brand Name :");
        car_brand_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_brand_btnActionPerformed(evt);
            }
        });

        car_ser_no_btn.setText("Search via Car Serial Number :");
        car_ser_no_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_ser_no_btnActionPerformed(evt);
            }
        });

        model_btn.setText("Search Car via Model Number :");
        model_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_btnActionPerformed(evt);
            }
        });

        mfg_btn.setText("List Of cars manufactured in the year :");
        mfg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfg_btnActionPerformed(evt);
            }
        });

        expired_mfg_btn.setText("Cars with expired mfg certificate :");
        expired_mfg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expired_mfg_btnActionPerformed(evt);
            }
        });

        nearest_car_btn.setText("Find nearest car to my location :");
        nearest_car_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearest_car_btnActionPerformed(evt);
            }
        });

        list_car_brands_btn.setText("List all the Car Brands :");
        list_car_brands_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_car_brands_btnActionPerformed(evt);
            }
        });

        UnavailCars_label.setText("Unavailabe Cars:");

        back_btn.setText("<<Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        catupd_btn.setText("Last time Catalog was updated :");
        catupd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catupd_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("max");

        jLabel2.setText("min");

        jLabel4.setText("Brands");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avail_cars_label)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(back_btn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(catupd_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(catupd_field, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(Search_serialno_label)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(display_label)
                                            .addComponent(SearchModel_label)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(availcars_label)
                                                        .addGap(384, 384, 384))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(count_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(maxmin_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(104, 104, 104)))
                                                .addComponent(max_min_label))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(car_ser_no_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(model_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(mfg_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                                                .addComponent(car_brand_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(list_car_brands_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nearest_car_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                                            .addComponent(avail_cars_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SearchBrand_Field)
                                            .addComponent(car_ser_no_field)
                                            .addComponent(model_field)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Max_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(Min_field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(man_yeartxt))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(287, 287, 287)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(179, 179, 179)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(availCars_label)
                                                    .addComponent(UnavailCars_label))
                                                .addGap(44, 44, 44)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(availCars_field, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(UnavailCars_field, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(expired_mfg_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(453, 453, 453)
                                        .addComponent(Brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(348, 348, 348))
                    .addComponent(SearchBrand_label, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back_btn)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(avail_cars_label)
                                    .addComponent(avail_cars_btn))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(2, 2, 2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(max_min_label)
                            .addComponent(Max_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Min_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxmin_btn))
                        .addGap(18, 18, 18)
                        .addComponent(display_label)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(SearchBrand_label)
                                .addGap(117, 117, 117)
                                .addComponent(Search_serialno_label))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(count_btn)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(car_brand_btn)
                                    .addComponent(SearchBrand_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(car_ser_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(car_ser_no_btn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mfg_btn)
                            .addComponent(man_yeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availCars_field, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availCars_label))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model_btn)
                            .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UnavailCars_label)
                            .addComponent(UnavailCars_field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(availcars_label)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchModel_label)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(expired_mfg_btn)
                                    .addComponent(Brandtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(catupd_btn)
                                    .addComponent(catupd_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(nearest_car_btn)
                        .addGap(31, 31, 31)
                        .addComponent(list_car_brands_btn)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void avail_cars_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avail_cars_btnActionPerformed
        // TODO add your handling code here:
       ArrayList<CarDetails> list = new ArrayList<CarDetails>();
       for(CarDetails Carr : cd.getCar() )   // add matched element to list and populate table 
       {
           if(Carr.getAvail_car().equalsIgnoreCase("Yes"))
           {
               list.add(Carr);
               populatetable1(list);
           }
           
       }
    }
       private void populatetable1(ArrayList<CarDetails>alist)
       {
           DefaultTableModel dtm=(DefaultTableModel)Car_table2.getModel();
        dtm.setRowCount(0);
        for(CarDetails Carr : alist)
        {
            Object[]row=new Object[8];
            row[0]=Carr;
            row[1]=Carr.getCar_Manufacturers();
            row[2]=Carr.getSerial_Number();
            row[3]=Carr.getSeating_capacity();
            row[4]=Carr.getCar_City();
            row[5]=Carr.getYear_Manufacture();
            row[6]=Carr.getAvail_car();
            row[7]=Carr.getCar_Expired();
            
            
            dtm.addRow(row);
            
        }
           
    }//GEN-LAST:event_avail_cars_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout=(CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_back_btnActionPerformed

    private void maxmin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxmin_btnActionPerformed
        // TODO add your handling code here:
        
        int max=Integer.parseInt(Max_field.getText());
        
        int min=Integer.parseInt(Min_field.getText());
   
         ArrayList<CarDetails> list1 = new ArrayList<CarDetails>();
         for(CarDetails Carr : cd.getCar())
         {
             if(min<=Carr.getSeating_capacity()&&Carr.getSeating_capacity()<=max)
             {
                 list1.add(Carr);
                 populatetable1(list1);
             }
         }
        
    }//GEN-LAST:event_maxmin_btnActionPerformed

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
        // TODO add your handling code here:
          int count=0;
          int count1=0;
         for(CarDetails Carr : cd.getCar())
            
         {
             if(Carr.getAvail_car().equalsIgnoreCase("Yes"))
                 count=count+1;
             else
             {
                 count1=count1+1;
             }
         }
         availCars_field.setText(count+"");
         UnavailCars_field.setText(count1+"");
         
    }//GEN-LAST:event_count_btnActionPerformed

    private void car_brand_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_brand_btnActionPerformed
        // TODO add your handling code here:
       String brand=SearchBrand_Field.getText();
       ArrayList<CarDetails> list2 = new ArrayList<CarDetails>();
       for(CarDetails Carr : cd.getCar() )
       {
           if(Carr.getCar_Manufacturers().equals(brand))
           {
               list2.add(Carr);
               populatetable1(list2);
           }
       }
    }//GEN-LAST:event_car_brand_btnActionPerformed

    private void car_ser_no_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_ser_no_btnActionPerformed
        // TODO add your handling code here:
        String sno=car_ser_no_field.getText();
         ArrayList<CarDetails> list3 = new ArrayList<CarDetails>();
       for(CarDetails Carr : cd.getCar() )
       {
           if(Carr.getSerial_Number().equals(sno))
           {
               list3.add(Carr);
               populatetable1(list3);
           }
       }
    }//GEN-LAST:event_car_ser_no_btnActionPerformed

    private void model_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_btnActionPerformed
        // TODO add your handling code here:
        int mod=Integer.parseInt(model_field.getText());
         ArrayList<CarDetails> list4 = new ArrayList<CarDetails>();
       for(CarDetails Carr : cd.getCar() )
       {
           if(Carr.getModel_Number()==mod)
           {
               list4.add(Carr);
               populatetable1(list4);
           }
       }
    }//GEN-LAST:event_model_btnActionPerformed

    private void mfg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfg_btnActionPerformed
        // TODO add your handling code here:
        int year=Integer.parseInt(man_yeartxt.getText());
        ArrayList<CarDetails> list5 = new ArrayList<CarDetails>();
       for(CarDetails Carr : cd.getCar() )
       {
           if(Carr.getYear_Manufacture()==year)
           {
               list5.add(Carr);
               populatetable1(list5);
           }
       }
        
    }//GEN-LAST:event_mfg_btnActionPerformed

    private void expired_mfg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expired_mfg_btnActionPerformed
        // TODO add your handling code here:
         ArrayList<CarDetails> list6 = new ArrayList<CarDetails>();
       for(CarDetails Carr : cd.getCar() )   // add matched element to list and populate table 
       {
           if(Carr.getCar_Expired().equalsIgnoreCase("Yes"))
           {
               list6.add(Carr);
               populatetable1(list6);
           }
           
       }
        
    }//GEN-LAST:event_expired_mfg_btnActionPerformed

    private void catupd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catupd_btnActionPerformed
        // TODO add your handling code here:
         Date c;
         c=cd.getCar().get(0).getCreated_On();
         SimpleDateFormat s=new SimpleDateFormat("HH:mm:ss");
         for(CarDetails Carr : cd.getCar())
         {
             if(Carr.getCreated_On().compareTo(c)>0)
             {
                 catupd_field.setText(s.format(Carr.getCreated_On()));
             }
              if(Carr.getCreated_On().compareTo(c)<0)
             {
                 catupd_field.setText(s.format(c));
             }
               if(Carr.getCreated_On().compareTo(c)==0)
             {
                 catupd_field.setText(s.format(Carr.getCreated_On()));
             }
         }    
    }//GEN-LAST:event_catupd_btnActionPerformed

    private void nearest_car_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearest_car_btnActionPerformed
        // TODO add your handling code here:
        ArrayList<CarDetails> list10 = new ArrayList<CarDetails>();
        for(CarDetails Carr : cd.getCar() )   // add matched element to list and populate table 
       {
           if(Carr.getYear_Manufacture()==2019)
           {
               list10.add(Carr);
               populatetable1(list10);
           }
           
       }
    }//GEN-LAST:event_nearest_car_btnActionPerformed

    private void list_car_brands_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_car_brands_btnActionPerformed
        // TODO add your handling code here:
       ArrayList<String> list9 = new ArrayList<String>();
       for(CarDetails Carr : cd.getCar() )
       {    
       
          if(list9.contains(Carr.getCar_Manufacturers()))
          {
              
          }
          else
          {
              list9.add(Carr.getCar_Manufacturers());
          }
        }
//       for(String i : list9)
//       {
       Brandtxt.setText(list9.toString());
//       }
      
    }//GEN-LAST:event_list_car_brands_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Brandtxt;
    private javax.swing.JTable Car_table2;
    private javax.swing.JTextField Max_field;
    private javax.swing.JTextField Min_field;
    private javax.swing.JTextField SearchBrand_Field;
    private javax.swing.JLabel SearchBrand_label;
    private javax.swing.JLabel SearchModel_label;
    private javax.swing.JLabel Search_serialno_label;
    private javax.swing.JTextField UnavailCars_field;
    private javax.swing.JLabel UnavailCars_label;
    private javax.swing.JTextField availCars_field;
    private javax.swing.JLabel availCars_label;
    private javax.swing.JButton avail_cars_btn;
    private javax.swing.JLabel avail_cars_label;
    private javax.swing.JLabel availcars_label;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton car_brand_btn;
    private javax.swing.JButton car_ser_no_btn;
    private javax.swing.JTextField car_ser_no_field;
    private javax.swing.JButton catupd_btn;
    private javax.swing.JTextField catupd_field;
    private javax.swing.JButton count_btn;
    private javax.swing.JLabel display_label;
    private javax.swing.JButton expired_mfg_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton list_car_brands_btn;
    private javax.swing.JTextField man_yeartxt;
    private javax.swing.JLabel max_min_label;
    private javax.swing.JButton maxmin_btn;
    private javax.swing.JButton mfg_btn;
    private javax.swing.JButton model_btn;
    private javax.swing.JTextField model_field;
    private javax.swing.JButton nearest_car_btn;
    // End of variables declaration//GEN-END:variables
}
