/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Business.CarAppDir;
import Business.CarDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anish
 */
public class MngJpanel extends javax.swing.JPanel {

    /**
     * Creates new form MngJpanel
     */
    private JPanel rightpanel;
    private CarAppDir cd;

    MngJpanel(JPanel rightpanel, CarAppDir cd) {
        initComponents();
        this.rightpanel=rightpanel;
        this.cd=cd;
        populateTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Car_Table = new javax.swing.JTable();
        view_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        create_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        search_Field = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();

        Car_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model", "Brand", "Serial ", "Seating", "City", "Year", "Avail", "Expired"
            }
        ));
        jScrollPane1.setViewportView(Car_Table);

        view_btn.setText("View");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        create_btn.setText("Create");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(create_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(21, 21, 21)
                        .addComponent(view_btn)
                        .addGap(18, 18, 18)
                        .addComponent(delete_btn)
                        .addGap(18, 18, 18)
                        .addComponent(create_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout=(CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_backbtnActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        // TODO add your handling code here:
        CreateJPanel panel=new CreateJPanel(rightpanel,cd);
        rightpanel.add("CreateJPanel",panel);
        CardLayout layout=(CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
    }//GEN-LAST:event_create_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow=Car_Table.getSelectedRow();
        if(selectedRow>=0)
        {
            int dialogbutton=JOptionPane.YES_OPTION;
            int dialogresult=JOptionPane.showConfirmDialog(null,"Would like to really delete","Warning",JOptionPane.WARNING_MESSAGE);
            if(dialogresult==JOptionPane.YES_OPTION)
            {
                CarDetails Carr=(CarDetails)Car_Table.getValueAt(selectedRow,0);
                cd.deleteCar(Carr);
                populateTable();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the table","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here:
        int selectedRow=Car_Table.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the table","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            CarDetails Carr=(CarDetails)Car_Table.getValueAt(selectedRow,0);
            ViewJPanel panel=new ViewJPanel(rightpanel,Carr);
            rightpanel.add("ViewJPanel",panel);
            CardLayout layout=(CardLayout)rightpanel.getLayout();
            layout.next(rightpanel);
            
        }
        
    }//GEN-LAST:event_view_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        CarDetails result=cd.searchcar(search_Field.getText());
        if(result==null)
        {
             JOptionPane.showMessageDialog(null,"Please select appropriately","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {

            ViewJPanel panel=new ViewJPanel(rightpanel,result);
            rightpanel.add("ViewJPanel",panel);
            CardLayout layout=(CardLayout)rightpanel.getLayout();
            layout.next(rightpanel);
        }
    }//GEN-LAST:event_search_btnActionPerformed
    
     private void populateTable()
    {
        DefaultTableModel dtm=(DefaultTableModel)Car_Table.getModel();
        dtm.setRowCount(0);
        for(CarDetails Carr : cd.getCar())
        {
            Object[]row=new Object[8];
            row[0]=Carr;
            row[1]=Carr.getCar_Manufacturers();
            row[2]=Carr.getSerial_Number();
            row[3]=Carr.getSeating_capacity();
            row[4]=Carr.getCar_City();
            row[5]=Carr.getYear_Manufacture();
            row[6]=Carr.getAvail_car();
            row[7]=Carr.getCar_Expired();
            
            
            dtm.addRow(row);
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Car_Table;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton create_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_Field;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
