/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Business.CarAppDir;
import Business.CarDetails;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author anish
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel rightpanel;
    private CarDetails Carr;
   

    ViewJPanel(JPanel rightpanel, CarDetails Carr) {
         initComponents();
         this.rightpanel=rightpanel;
         this.Carr=Carr;
         populateCarDetails();
         btn_save.setEnabled(false);
         update_btn.setEnabled(true);
    }
                                     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        View_label = new javax.swing.JLabel();
        Modelno_label = new javax.swing.JLabel();
        txt_model = new javax.swing.JTextField();
        Brand_label = new javax.swing.JLabel();
        txt_company = new javax.swing.JTextField();
        serialno_label = new javax.swing.JLabel();
        txt_serno = new javax.swing.JTextField();
        no_seats_label = new javax.swing.JLabel();
        txt_manu = new javax.swing.JTextField();
        nsa_label = new javax.swing.JLabel();
        txt_seats = new javax.swing.JTextField();
        city_label = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        dmc_label = new javax.swing.JLabel();
        txt_expired = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_avail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        View_label.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        View_label.setText("View Car Details");

        Modelno_label.setText("Model Number :");

        txt_model.setEnabled(false);

        Brand_label.setText("Company Name: ");

        txt_company.setEnabled(false);

        serialno_label.setText("Serial Number :");

        txt_serno.setEnabled(false);

        no_seats_label.setText("Manufactured date:");

        txt_manu.setEnabled(false);

        nsa_label.setText("Number of seats available: ");

        txt_seats.setEnabled(false);

        city_label.setText("City :");

        txt_city.setEnabled(false);

        dmc_label.setText("Expired Certificates :");

        txt_expired.setEnabled(false);

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.setEnabled(false);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel1.setText("Availability :");

        txt_avail.setEnabled(false);

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btn_save)
                        .addGap(64, 64, 64)
                        .addComponent(update_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(159, 159, 159)
                                .addComponent(View_label))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Modelno_label)
                                    .addComponent(Brand_label)
                                    .addComponent(serialno_label)
                                    .addComponent(no_seats_label)
                                    .addComponent(city_label)
                                    .addComponent(dmc_label)
                                    .addComponent(jLabel1)
                                    .addComponent(nsa_label))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_model)
                                    .addComponent(txt_company)
                                    .addComponent(txt_serno)
                                    .addComponent(txt_manu)
                                    .addComponent(txt_seats)
                                    .addComponent(txt_city)
                                    .addComponent(txt_expired, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(txt_avail))))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(View_label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelno_label)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Brand_label)
                    .addComponent(txt_company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialno_label)
                    .addComponent(txt_serno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nsa_label)
                    .addComponent(txt_seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(city_label)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(no_seats_label)
                    .addComponent(txt_manu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_avail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_expired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dmc_label))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(update_btn))
                .addGap(18, 121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateCarDetails()
    {
        txt_model.setText(Carr.getModel_Number()+"");
        txt_company.setText(Carr.getCar_Manufacturers());
        txt_serno.setText(Carr.getSerial_Number());
        txt_manu.setText(Carr.getSeating_capacity()+"");
        txt_seats.setText(Carr.getMin_Max_Seats()+"");
        txt_city.setText(Carr.getCar_City());
        txt_expired.setText(Carr.getCar_Expired()+"");
        txt_avail.setText(Carr.getAvail_car()+"");
    }
    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        txt_model.setEnabled(true);
        txt_company.setEnabled(true);
        txt_serno.setEnabled(true);
        txt_manu.setEnabled(true);
        txt_seats.setEnabled(true);
        txt_city.setEnabled(true);
        txt_expired.setEnabled(true);
        txt_avail.setEnabled(true);
        btn_save.setEnabled(true);
        update_btn.setEnabled(false);
          try{
        Integer.parseInt(txt_model.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid model name");
                return;
        }
          try{
        Integer.parseInt(txt_manu.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid brand name");
                return;
        }
        try{
        Integer.parseInt(txt_seats.getText());
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid seating capacity");
                return;
        }
        if(txt_company.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid company name");
                return;
                }
        if(txt_serno.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid serial number");
                return;
                }
        if(txt_city.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid city");
                return;
                }
        if(txt_expired.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid expiry case");
                return;
                }
        if(txt_avail.getText().isEmpty())
                {
                JOptionPane.showMessageDialog(null,"Please enter a valid availability case");
                return;
                }
        
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        Carr.setModel_Number(Integer.parseInt(txt_model.getText()));
        Carr.setCar_Manufacturers(txt_company.getText());
        Carr.setSerial_Number(txt_serno.getText());
        Carr.setSeating_capacity(Integer.parseInt(txt_manu.getText()));
        Carr.setMin_Max_Seats(Integer.parseInt(txt_seats.getText()));
        Carr.setCar_City(txt_city.getText());
        Carr.setCar_Expired(txt_expired.getText());
        Carr.setAvail_car(txt_avail.getText());
        JOptionPane.showMessageDialog(null," Successfully Updated!!");
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        CardLayout layout=(CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Brand_label;
    private javax.swing.JLabel Modelno_label;
    private javax.swing.JLabel View_label;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel city_label;
    private javax.swing.JLabel dmc_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel no_seats_label;
    private javax.swing.JLabel nsa_label;
    private javax.swing.JLabel serialno_label;
    private javax.swing.JTextField txt_avail;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_company;
    private javax.swing.JTextField txt_expired;
    private javax.swing.JTextField txt_manu;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_seats;
    private javax.swing.JTextField txt_serno;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
