/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Car_Interface;

/**
 *
 * @author anish
 */
import Car_Product.Car_Details;
public class Car_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Car_Frame
     */
    private Car_Details Car_Object;
    public Car_Frame() {
        initComponents();
        Car_Object=new Car_Details();//created an object of Car_Details
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Split_Jpanel = new javax.swing.JSplitPane();
        Control_Jpanel = new javax.swing.JPanel();
        Create_btn = new javax.swing.JButton();
        View_btn = new javax.swing.JButton();
        Display_Jpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Create_btn.setText("Create");
        Create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_btnActionPerformed(evt);
            }
        });

        View_btn.setText("View");
        View_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Control_JpanelLayout = new javax.swing.GroupLayout(Control_Jpanel);
        Control_Jpanel.setLayout(Control_JpanelLayout);
        Control_JpanelLayout.setHorizontalGroup(
            Control_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JpanelLayout.createSequentialGroup()
                .addGroup(Control_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Create_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        Control_JpanelLayout.setVerticalGroup(
            Control_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Control_JpanelLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(Create_btn)
                .addGap(83, 83, 83)
                .addComponent(View_btn)
                .addGap(229, 229, 229))
        );

        Split_Jpanel.setLeftComponent(Control_Jpanel);

        javax.swing.GroupLayout Display_JpanelLayout = new javax.swing.GroupLayout(Display_Jpanel);
        Display_Jpanel.setLayout(Display_JpanelLayout);
        Display_JpanelLayout.setHorizontalGroup(
            Display_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        Display_JpanelLayout.setVerticalGroup(
            Display_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        Split_Jpanel.setRightComponent(Display_Jpanel);

        getContentPane().add(Split_Jpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_btnActionPerformed
        // TODO add your handling code here:
        Create_JPanel Create_obj=new Create_JPanel(Car_Object);//Created an Object of Create Panel
        Split_Jpanel.setRightComponent(Create_obj);
    }//GEN-LAST:event_Create_btnActionPerformed

    private void View_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_btnActionPerformed
        // TODO add your handling code here:
        View_JPanel View_obj=new View_JPanel(Car_Object);//Created an object of View Panel
        Split_Jpanel.setRightComponent(View_obj);
    }//GEN-LAST:event_View_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Control_Jpanel;
    private javax.swing.JButton Create_btn;
    private javax.swing.JPanel Display_Jpanel;
    private javax.swing.JSplitPane Split_Jpanel;
    private javax.swing.JButton View_btn;
    // End of variables declaration//GEN-END:variables
}
